name: deploy

on:
  push:
    branches:
      - master
      - ci

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/katarina.pem
          sudo chmod 600 ./.ssh/katarina.pem
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}

      - name: Create env file
        run: |
          mkdir -p env
          cd env
          touch lookenv.dev.js lookenv.prod.js
          echo "${{secrets.ENV_DEV}}" >> lookenv.dev.js
          echo "${{secrets.ENV_PROD}}" >> lookenv.prod.js

      - name: Install PM2
        run: npm i pm2

      - name: Deploy
        run: npm run deploy